# -*- coding: utf-8 -*-

{
    "name": "Madeco Droits - MADECO",
    "sequence": '0',
    "version": "15.0.0.0.1",
    "author": "APIK - Michel Guiheneuf",
    "website": "http://www.apik.cloud",
    "license": "AGPL-3",
    "category": "Vertical",
    "description": "Madeco Droits - MADECO",
    "summary": "Madeco Droits - MADECO",
    "depends": [
        'base',
        # 'mrp',
        'purchase',
        'sale',
        'sales_team',
        'stock',
        'mail',
        'product',
        'sale_mrp',
        'madeco_partner',
        'madeco_product',
        'madeco_achat',
        'madeco_vente',
        'madeco_barcode',
        'madeco_compta',
        'madeco_mrp',
        'madeco_stock',
        'madeco_stock_sscc',
        'madeco_transport',
        'madeco_usability',
        'apik_edi',
        'apik_prestashop',
        'apik_pdp',
        'customer_product_code',
        'apik_relance_centrale',
    ],
    "data": [
        "data/res.groups.csv",
        "data/ir.model.access.csv",
        "data/ir.ui.menu.csv",
        "data/ir.rule.csv",
        "data/ir.ui.view.csv",
        "views/sale_order.xml",
        "views/purchase_order.xml",
        "views/stock.xml",
        "views/mrp.xml",
        "views/account_move.xml",
    ],
    "demo": [
	    
    ],
    'qweb': [
        	    
    ],
    'installable': True,
	'application':True,
    'auto_install':False,
}
